### ISSUE TITLE
Recover wallet footer text font too small

### ISSUE THREAD

**Issue by pgarciagon** [joticajulian/kondor#30]
Browser: chrome Version 100.0.4896.88 (Official Build) (x86_64)
OS: macOS  10.4

On the main form, the footer text on the "recover wallet" form ("creating a wallet and importing
using 12 word phrase coming soon") is too small and can not be read

See screenshot: 

![telegram-cloud-photo-size-2-5389042268729621584-x](https://user-images.githubusercontent.com/203416/163593053-c867bf06-cdba-4684-991d-fe59d80983e3.jpg)

**Comment by brklyn8900** [comment]
resolved in issue #31
