### ISSUE TITLE
Wrong size of the Signature Request and send pop-up window.

### ISSUE THREAD

**Issue by pgarciagon** [joticajulian/kondor#56]
On  macOS using Chorme Version 108.0.5359.94 (Official Build) (x86_64):
The pop up window to unlock the sign actions opens undersized compared to the content which is seeing clipped away. See attached screenshot:

![signature_request_and_send](https://user-images.githubusercontent.com/203416/206162166-73c60be3-a10d-4a3d-b7f0-b21ca892dfae.png)

**Comment by joticajulian** [comment]
fixed in new versions
