### ISSUE TITLE
Update frontend of dashboard to support dApps

### ISSUE THREAD

**Issue by joticajulian** [joticajulian/kondor#64]
We want to introduce more dApps in Kondor Wallet. Then the new design consists in a dashboard with a widget at the top and a list of dApps.

This is the current status
<img width="265" alt="image" src="https://github.com/joticajulian/kondor/assets/25859602/daf61537-ea9d-47cb-ac9d-53438dbdf3aa">

And this is the new design for the dashboard (see https://github.com/joticajulian/kondor/blob/main/src/index/views/4-Dashboard.vue)
<img width="214" alt="image" src="https://github.com/joticajulian/kondor/assets/25859602/d6777d2e-af25-4cea-8aac-34eef8a85a7b">

The new design must consist in a set of components:
1. Nav: No need to change this part.
2. Widget of Tokens: It has the current balance of Koin. And below it has a list of token icons. These icons have a tooltip showing the balance of each one. When the user clicks on the icon the token is displayed in the widget by replacing the Koin balance.
3. Section of dApp icons that will trigger new pages dedicated to each dApp.

Initially the wallet will start with these tokens: Koin, VHP, and Vapor.

This task corresponds just to the html and css work. The JS code is a good to have but not required.

Create a PR to merge into the dev branch.

**Comment by gyauelvis** [comment]
I would love to take this project but the problem is i don't understand the issue. Could you please explain it better. 
I understand you want to update the frontend of your dashboard but which part do you want to update specifically could you be clear about that.

**Comment by joticajulian** [comment]
implemented in v0.9.0
