### ISSUE TITLE
New page to add tokens

### ISSUE THREAD

**Issue by joticajulian** [joticajulian/kondor#66]
Create the /tokens/add page with this design:

<img width="212" alt="image" src="https://github.com/joticajulian/kondor/assets/25859602/a993b05b-2bca-42af-935a-f576151916db">

This task corresponds just to the html and css work. The JS code is a good to have but not required.

Create a PR to merge into the dev branch.

**Comment by mklno** [comment]
I am new to open-source, can the design be implemented with plain html and css, could you please clarify?

**Comment by joticajulian** [comment]
Thanks for taking a look.

- create a copy of [this file](https://github.com/joticajulian/kondor/blob/main/src/index/views/5-Signers.vue) and update the html in the `<template>`.
- import it in [the router.js file](https://github.com/joticajulian/kondor/blob/main/src/index/router.js) and define the path /tokens/add for this page
- for the CSS update this file [kondor.css](https://github.com/joticajulian/kondor/blob/main/src/shared/assets/css/kondor.css). Try to reuse the classes that already exist there. Update them if needed, or create new ones.

Check in the readme "Run as Single-Page Application" to see the results. Your page should be in http://localhost:8080/#/tokens/add

**Comment by gyauelvis** [comment]
The design here is just for small screen devices, do you need to work on the big screen designs too.

**Comment by joticajulian** [comment]
for this task no.
For the moment the extension is just a popup in the webpage. But in the future it is possible to create a wide screen webpage.

**Comment by gyauelvis** [comment]
I have forked your repository but I'm it so difficult setting up your project on my local machine. I'm having so many errors installing the dependencies

**Comment by joticajulian** [comment]
which types of errors? what is your operating system?

**Comment by gyauelvis** [comment]
windows.

**Comment by joticajulian** [comment]
check if you have Nodejs v16 or higher

**Comment by gyauelvis** [comment]
Yes I have 18.17.0

**Comment by joticajulian** [comment]
show me the list of errors

**Comment by gyauelvis** [comment]
> kondor@0.8.1 build:3rdpage
> copyfiles -u 3 node_modules/koilib/dist/koinos.min.js 3rdpage/js && copyfiles -u 3 node_modules/kondor-js/dist/kondor.min.js 3rdpage/js

'copyfiles' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\LENOVO\Desktop\hacktoberfest\kondor> npm cache clean --force
>>
npm WARN using --force Recommended protections disabled.
PS C:\Users\LENOVO\Desktop\hacktoberfest\kondor> npm install -g npm@latest
>>

added 1 package in 46s

28 packages are looking for funding
  run `npm fund` for details
PS C:\Users\LENOVO\Desktop\hacktoberfest\kondor> npm install              
>> npm run build:3rdpage
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: kondor@0.8.1
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.15
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"~4.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\LENOVO\AppData\Local\npm-cache\_logs\2023-10-01T22_08_02_982Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\LENOVO\AppData\Local\npm-cache\_logs\2023-10-01T22_08_02_982Z-debug-0.log

> kondor@0.8.1 build:3rdpage
> copyfiles -u 3 node_modules/koilib/dist/koinos.min.js 3rdpage/js && copyfiles -u 3 node_modules/kondor-js/dist/kondor.min.js 3rdpage/js

'copyfiles' is not recognized as an internal or external command,
operable program or batch file.

**Comment by joticajulian** [comment]
mm something is wrong with that package. Anyway, don't follow these instructions.
Follow the steps in [Extension Developers](https://github.com/joticajulian/kondor#extension-developers) -> Run as single-page application.

**Comment by gyauelvis** [comment]
sure. will do that

**Comment by joticajulian** [comment]
implemented in v0.9.0
