### ISSUE TITLE
[BUG] Can't add token without decimals

### ISSUE THREAD

**Issue by vonlooten** [joticajulian/kondor#68]
## Current behavior
I found out that adding tokens without decimals did not work. 
An error message appeared `token without decimals`

## Expected behavior
It should be possible to add tokens that have decimal places or not.
## Steps to reproduce
A token without decimals is KDBLN it has the contract address `1Noy4JD7F6ByUwMmbKPo1o2JVko9CzB6Eu` 
The error message will show up if you add this token address 

## Screenshot
![image](https://github.com/joticajulian/kondor/assets/5501855/91f3b319-8411-44cd-be68-fdda58d25cd3)

**Comment by joticajulian** [comment]
Thanks for reporting. Fixed in version 0.9.1
